# Generated by Django 4.0.2 on 2022-03-03 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_comments_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projects'),
        ),
    ]
