# Generated by Django 4.0.2 on 2022-03-22 19:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0001_initial"),
        ("api", "0006_rename_author_user_id_comments_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="contribution",
            field=models.ManyToManyField(
                related_name="contributions",
                through="api.Contributors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
