# Generated by Django 4.0.2 on 2022-03-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_projects_contribution"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projects",
            name="contribution",
        ),
    ]
